### ISSUE TITLE
Cambiar logo corfo

### ISSUE THREAD

**Issue by camargozzini** [ciudadanointeligente/fima#49]

**Comment by jbci** [comment]
![image](https://cloud.githubusercontent.com/assets/17278568/26159509/bdabf5cc-3aec-11e7-8f82-84412513cfd4.png)
![image](https://cloud.githubusercontent.com/assets/17278568/26159525/c630eae0-3aec-11e7-897a-e32ebd0fafc8.png)
![image](https://cloud.githubusercontent.com/assets/17278568/26159532/cba7d75e-3aec-11e7-976a-969e875b08ee.png)
